os:
  - linux

language: cpp
dist: xenial

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -q

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - catch
      - cmake
      - doxygen
      - cppcheck

branches:
  only:
    - master
    - devel

script:

  - export CC=gcc-5;
  - export CXX=g++-5;
  - mkdir -p build && cd build
  - cmake -DWITH_TESTS=yes ..
  - make unit_tests -j 4
  - make test
